name: Quality

on:
  push:
    branches:
      - main
  pull_request_target:

jobs:
  golangci:
    name: GolangCI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: GolangCI
        uses: golangci/golangci-lint-action@v3
